package logicsim;

public enum Lang {
	ABORTED, ABOUT, ADDPOINT, ADDPOINT_HELP, BASIC, CANCEL, CONNECTED, DELETE, DESCRIPTION, DONTSAVE,
	EXIT, EXPORT, FILE, FILENOTFOUND, FLIPFLOPS, GATEDESIGN, GATEDESIGN_ANSI, GATEDESIGN_IEC, HELP, INPUTHIGH,
	INPUTHIGH_HELP, INPUTINV, INPUTINV_HELP, INPUTLOW, INPUTLOW_HELP, INPUTNORM, INPUTNORM_HELP, INPUTS,
	LANGUAGE, LSRESTART, MIRROR, MODULE, MODULECREATE, MODULENOTFOUND, MODULES, NAME, NEW, NO, NOMODULE, OK, OPEN,
	PAINTGRID, PARTSDELETED, PARTSSELECTED, PRINT, PROPERTIES, QUESTION_CONFIRMDISCARD, QUESTION_CONFIRMSAVE,
	QUESTION_DELETE, READERROR, REMOVEGATE, REMOVEPOINT, REMOVEPOINT_HELP, RESET, ROTATE, SAVE, SAVEAS, SAVECIRCUIT,
	SAVED, SAVEERROR, SELECT, SETTINGS, SIMULATE, UNNAMED, YES, ZOOMIN, ZOOMOUT
}
