package logicsim;

public enum Lang {
	ABORTED, ABOUT, ADDPOINT, ADDPOINT_HELP, AUTOWIRE, BASIC, CANCEL, CONNECTED, DELETE, DESCRIPTION, DONTSAVE, EDIT,
	EDITWIRE, EXIT, EXPERT, EXPORT, FILE, FILENOTFOUND, FLIPFLOPS, GATEDESIGN, GATEDESIGN_ANSI, GATEDESIGN_IEC,
	GATESETTINGS, HELP, INPUTHIGH, INPUTHIGH_HELP, INPUTINV, INPUTINV_HELP, INPUTLOW, INPUTLOW_HELP, INPUTNORM,
	INPUTNORM_HELP, INPUTS, LANGUAGE, LSRESTART, MIRROR, MODE, MODULE, MODULECREATE, MODULENOTFOUND, MODULES, NAME, NEW,
	NEWWIRE, NEWWIRE_HELP, NO, NOMODULE, NORMAL, OK, OPEN, PAINTGRID, PARTSDELETED, PARTSSELECTED, PRINT,
	PROPERTIES, QUESTION_CONFIRMDISCARD, QUESTION_CONFIRMSAVE, QUESTION_DELETE, READERROR, REMOVEGATE,
	REMOVEPOINT, REMOVEPOINT_HELP, RESET, ROTATE, SAVE, SAVEAS, SAVECIRCUIT, SAVED, SAVEERROR, SELECT, SELECTALL,
	SELECTNONE, SETTINGS, SIMULATE, TEXT, UNNAMED, WIRE, YES, ZOOMIN, ZOOMOUT, ALREADYMODULE
}
