package logicsim;

public enum Lang {
	ABORTED, ABOUT, ADDPOINT, ADDPOINT_HELP, ALREADYMODULE, AUTOWIRE, BASIC, CANCEL, COLORMODE, COLORMODE_ON,
	COLORMODE_OFF, CONNECTED, DELETE, DESCRIPTION, DONTSAVE, EDIT, EXIT, EXPERT, EXPORT, FILE, FILENOTFOUND, FLIPFLOPS,
	GATEDESIGN, GATEDESIGN_ANSI, GATEDESIGN_IEC, GATESETTINGS, HELP, INPUTHIGH, INPUTHIGH_HELP, INPUTINV, INPUTINV_HELP,
	INPUTLOW, INPUTLOW_HELP, INPUTNORM, INPUTNORM_HELP, INPUTS, LANGUAGE, LSRESTART, MIRROR, MODE, MODULE, MODULECREATE,
	MODULENOTFOUND, MODULES, NAME, NEW, NO, NOMODULE, NORMAL, OK, OPEN, PAINTGRID, PARTSDELETED, PARTSSELECTED, PIN,
	PRINT, PROPERTIES, QUESTION_CONFIRMDISCARD, QUESTION_CONFIRMSAVE, QUESTION_DELETE, READERROR, REMOVEGATE,
	REMOVEPOINT, REMOVEPOINT_HELP, RESET, ROTATE, SAVE, SAVEAS, SAVECIRCUIT, SAVED, SAVEERROR, SELECT, SELECTALL,
	SELECTNONE, SETTINGS, SIMULATE, TEXT, UNNAMED, WIRE, WIREEDIT, WIRENEW, WIRENEW_HELP, WIREPOINT, YES, ZOOMALL,
	ZOOMIN, ZOOMOUT
}
